libraries:
  - name: numpy
    version: latest

  - name: jinja2
    version: latest

  - name: webapp2
    version: latest


application: urop-1210
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
  - url: /static
    static_dir: static

  - url: .*
    script: main.app
